### ISSUE TITLE
while running metric i it says Could not load dynamic library 'libnvinfer.so.7'; libnvinfer_plugin.so.7,    raise OSError( OSError: Distant resource does not have an ETag, we won't be able to reliably ensure reproducibility in google colab 

### ISSUE THREAD

**Issue by bhaveshk1502** [s-nlp/detox#7]
fairseq failing to install , then installed it via github clone 
![image](https://user-images.githubusercontent.com/81642316/228620321-922de33b-6467-4eec-a539-8dd0b2afc1b1.png)
then while running python metric.py --inputs PATH_TO_INPUTS --preds PATH_TO_PREDS this is the error which occurred, i tried fixing it but couldn't

(2023-03-29 17:23:24.118119: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-29 17:23:24.118281: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-29 17:23:24.118304: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Calculating style of predictions
Traceback (most recent call last):
  File "/content/fairseq/metric.py", line 161, in <module>
    accuracy_by_sent = classify_preds(args, preds)
  File "/content/fairseq/metric.py", line 33, in classify_preds
    tokenizer = RobertaTokenizer.from_pretrained(model_name)
  File "/usr/local/lib/python3.9/dist-packages/transformers/tokenization_utils_base.py", line 1692, in from_pretrained
    resolved_vocab_files[file_id] = cached_path(
  File "/usr/local/lib/python3.9/dist-packages/transformers/file_utils.py", line 1402, in cached_path
    output_path = get_from_cache(
  File "/usr/local/lib/python3.9/dist-packages/transformers/file_utils.py", line 1580, in get_from_cache
    raise OSError(
OSError: Distant resource does not have an ETag, we won't be able to reliably ensure reproducibility.)
![image](https://user-images.githubusercontent.com/81642316/228620742-1d231f35-3910-4c8e-86e0-8a9d1053f5ef.png)

Can you please take a look into this Mr David (@avidale ), thank you 

here is the colab notebook link for ref https://colab.research.google.com/drive/184al3-XSQqDrTY42Q9aGQy_OOwIfTPQQ?usp=sharing

**Comment by bhaveshk1502** [comment]
this error went away after using transformers latest version than one in requirements
